---
- name: demonstrate changed status
  hosts: all
  tasks:
  - name: check local time
    command: date
    register: command_result
# This will never report 'changed' status
# Команда date без конструкции ниже всегда будет отдавать статус 'changed' хотя на самом деле ничего не меняет
# Поэтому мы добавляем changed_when: False
    changed_when: false

  - name: print local time
    debug:
      var: command_result.stdout