---
- name: demo how register works
  hosts: all
  tasks:
    - name: show loop register
      shell: "echo {{ item }}"
      loop:
        - "one"
        - "two"
      register: echo   #сохраняет результат команды выше в переменную
    - name: show register results
      debug:
        var: echo