---
- name: Install remote facts
  hosts: all
  tasks:
    - name: include variables
      include_vars: lab-vars/facts-vars.yml
    - name: create remote directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: install new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
