---
- name: sample of stat and assert
  hosts: node2.example.com
  tasks:
    - name: stat a directory
      stat:
        path: /etc
      register: sta
    - name: show value of sta variable
      debug:
        var: sta
    - name: assert that /etc is a directory
      assert:
        that: sta.stat.isdir