---
- name: show how debug works
  hosts: node2.example.com
  tasks:
  - name: show value of a fact
    debug:
      msg: this system has {{ ansible_facts['memfree_mb'] }} available ram
  - name: register a result
    shell: /usr/bin/uptime
    register: result
  - name: show result of a registered variable
    debug:
      var: result
#      verbosity: 2