---
- name: simple block example
  hosts: all
  tasks:
    - name: setting up httpd
      block:
        - name: installing httpd
          dnf:
            name: httpd
            state: present
        - name: restart httpd
          service:
            name: httpd
            state: started
      when: ansible_distribution == "CentOS"