---
- name: create apache vhost
  hosts: node2.example.com

  roles:
    - role: apache-vhost

  post_tasks:
    - name: install contents from local file
      copy:
        src: /files/html/
        dest: "/var/www/vhosts/{{ ansible_hostname }}"
