---
- name: remove a specific cron job
  hosts: node2.example.com
  tasks:
    - name: remove a cron job
      cron:
        name: "write message to file"
        cron_file: keep-alive-messages
        state: absent
        user: ansible