---
- name: configure repository
  hosts: node2.example.com
  vars:
    my_package: nmap
  tasks:
  - name: connect to example repo
    yum_repository:
      name: lesson12
      description: "RHCE8 lesson 12 repo"
      file: lesson12
      baseurl: file:///run/media/ayakhin/CentOS-Stream-9-BaseOS-x86_64/BaseOS/
      gpgcheck: no
  
  - name: install package
    dnf:
      name: "{{ my_package }}"
      state: present

  - name: update package facts
    package_facts:
      manager: auto
    
  - name: show package facts for my_package
    debug:
      var: ansible_facts.packages[my_package]
    when: my_package in ansible_facts.packages