---
- name: test ftp upload
  hosts: localhost
  tasks:
  - name: install lftp
    dnf:
      name: lftp
  - name: upload file
    shell: >
      lftp node2.example.com <<EOF
      cd pub
      put /etc/hosts
      EOF